# Generated by Django 5.2.13 on 2026-04-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="allowed_targets",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
