# Generated by Django 5.2.13 on 2026-04-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0002_agent_allowed_targets"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="tunnel_secret",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
